name: Build

on: [push, pull_request]

jobs:
  Windows-VC:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        with: 
            repository: 'mruby/mruby'
            ref: '3.3.0'
        uses: actions/checkout@v4
      - name: Ruby version
        run: ruby -v
      - name: Download Config
        uses: valitydev/action-download-file@v1
        with:
          url: https://raw.githubusercontent.com/zekexiao/mruby-build/refs/heads/master/msvc.rb
          target-path: .
      - name: Build and test
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          rake MRUBY_CONFIG=msvc.rb
      - name: Upload
        with:
          path: build/host
        uses: actions/upload-artifact@v4
